apiVersion: v1
kind: Secret
metadata:
  name: trainbook-secrets
type: Opaque
data:
  DB_URL: bW9uZ29kYitzcnY6Ly9yZXNlcnZhdGlvbkFkbWluOk1BTkFHRVJAZ29kZnJleS1kYi1jbHVzdGVyLmNpdHdmNW4ubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUdvZGZyZXktREItQ2x1c3Rlcg==
  DB_NAME: cmVzZXJ2YXRpb24=  # 'reservation' encoded in base64

---
apiVersion: v1
kind: Service
metadata:
  name: trainbook-service
spec:
  selector:
    app: trainbook-app
    version: blue # This can be changed to "green" when switching traffic
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
